name: setup-cli
description: Setup Supabase CLI, supabase, on GitHub Actions runners
author: Supabase
inputs:
  version:
    description: Version of Supabase CLI to install
    required: false
    default: 0.32.1
runs:
  using: node16
  main: dist/index.js
